### ISSUE TITLE
Expand Example

### ISSUE THREAD

**Issue by allo-** [allo-/userjs-schema#2]
We need more examples:

- [x] Integer setting example
- [x] String setting example
  - String which is empty by default (i.e. ``general.useragent.override``), see https://github.com/allo-/firefox-profilemaker/issues/54 and https://github.com/allo-/firefox-profilemaker/commit/7496df9b32f4e97738d1d76a41c789788bf0b496 for why we need to care.
  - String which has a default string (i.e. different feedback urls)

**Comment by nodiscc** [comment]
@allo- you can either commit your examples directly to the file or send a PR like https://github.com/nodiscc/userjs-schema/pull/1, as you like

**Comment by allo-** [comment]
I am not too sure about your actual format. But this may depend on https://github.com/nodiscc/userjs-schema/issues/3.

**Comment by allo-** [comment]
I used ``"value_when_active": 0`` for the new setting without changing the old ones.

**Comment by allo-** [comment]
For the empyt=unset thing we can use "value=null" in the default json, BUT a user submitted form will contain the empty string. This means we need to fix the UI to either:

1) ``empty_means_unset`` interpretation on the server side.
2) Add a checkmark "unset" next to the input box in the UI

The first one means, that the empty string cannot be submitted by the user, even when it's possible (you actually CAN set the useragent to "" if you want to). The second one needs more UI and more logic to parse the submitted form on the server side, but supports all inputs (string, empty string, no change, explicity ``unset``).

**Comment by allo-** [comment]
https://github.com/nodiscc/userjs-schema/commit/e57e8594e4d2e39ccc68edb6f9d7b12de5f19605
Here you can see the rather unclean values:

    +      "value_when_active": "USERINPUT",
    +      "default": null,

the value(_when_active) should probably be parsed from the userinput coming from the browser, the ``default`` may be okay this way but we need to indicate not only that the default is unset, but give the user an option to set it to "unset" instead of "" or 0.

**Comment by nodiscc** [comment]
Copied from #4 


This is not fully what i needed (still the inverted category model).
But I thought about what we actually need to specify. Creating the best category/tag system here isn't really needed.

There is no need to have a common category system, sorting settings into categories isn't much work. What we need to collaborate is only a nice format for settings(-snippets) with descriptions and metadata like which features are broken by the settings.

Now looking at the current format for that purpose, it looks quite good. 
I am still no fan of having one setting per about:config key. For example [health report](https://github.com/allo-/firefox-profilemaker/blob/master/settings/health_report.json) has three settings to disable it. It doesn't make much sense to me to ask the user three times, just because this is split into finer settings at the about:config level.

Just a short recap for now, what's nice to have:

- [x] Name
- [x] Type
- [x] Title / short Description
- [ ] help text / long description
- [ ] (WIP) (List of) setting(s) and the values when the switch is active
- [x] A list of warnings (strings)
- [x] A list of references to read more about the setting
  - [ ] possibly an option to reference them in the description, like linking ``[1]``?
- [ ] A list of "breaks" tags (keywords, which don't change, like "copy-paste"), which can be mapped to a human readable name later.

**Comment by allo-** [comment]
Let's make this an own issue. The example is complete for everything we need to test.

**Comment by allo-** [comment]
See #6
